### PR TITLE
fix: #2517 trace simulate-sequence fallback against accumulated state

### LINKED ISSUE #2517: fix: simulate-sequence's state-overrides fallback traces calls against raw state, dropping earlier calls' writes
## Where

`lib/execute/simulate-sequence.ts`, `runWithStateOverrides` — the fallback path for chains whose RPC does not implement `eth_simulateV1`, introduced by #2452 (#2427).

For every call in the sequence, the loop runs:

1. `eth_call` and `eth_estimateGas` **with** `stateAtThisCall` (the accumulated state overrides from all earlier calls) — correct.
2. `debug_traceCall` with `prestateTracer` + `diffMode: true` to produce the state diff that seeds the next call — **without** any overrides:

```ts
provider.send("debug_traceCall", [
  tx,
  "latest",
  { tracer: "prestateTracer", tracerConfig: { diffMode: true } },
])
```

So the diff is computed against the raw `latest` chain state, not against the state the call was actually simulated against.

## Reason

`debug_traceCall` accepts `stateOverrides` in its options object (same per-account shape as `eth_call`'s third argument; geth `StateOverride`), so tracing against the accumulated state is supported. Without it:

- Any call that only succeeds because an earlier call set up state (approve before transferFrom, set-config before use, ...) **reverts inside the trace** even though the `eth_call` directly above it (run with the overrides) succeeded.
- Its `post` diff is then empty or wrong, `mergeDiffIntoOverrides` merges nothing, and every later call silently answers against state that lacks the earlier calls' writes.

The answer is internally inconsistent: the sequence reports call N as success (from the overridden `eth_call`) while not carrying call N's state into call N+1. That is exactly the failure mode this fallback exists to avoid — the feature's commit message says a node offering neither mechanism should report the later calls as unavailable "rather than quietly answering against latest state".

## Scope

- Fallback path only (chains without `eth_simulateV1`); the primary path is unaffected.
- Only from the 2nd call onward: the first call has nothing to carry, and a 2-call sequence never consumes the last call's diff — so the canonical approve→deposit pair answers correctly today.
- 3+ call sequences where an intermediate call depends on earlier state are wrong (e.g. approve → transferFrom → read balance: the read returns the pre-transfer balance). `MAX_SEQUENCE_CALLS` is 10, so this is reachable through `POST /api/execute/contract-call` with `simulate: true` and `calls[]`.

## Proposed fix

Pass the same snapshot to the trace:

```ts
{
  tracer: "prestateTracer",
  tracerConfig: { diffMode: true },
  ...(Object.keys(stateAtThisCall).length > 0 && { stateOverrides: stateAtThisCall }),
}
```

If a node that supports `debug_traceCall` rejects `stateOverrides`, the existing catch already degrades the remaining calls to `unavailable` — better than state-blind answers.

## Test

Assert in `tests/unit/execute-simulate-sequence.test.ts` that the second `debug_traceCall` request carries the first call's accumulated `stateOverrides`, while the first request sends none.

### PR DESCRIPTION
**Pull request by grantyuan**
## Summary

Fixes #2517.

In the simulate-sequence state-overrides fallback (chains whose RPC lacks `eth_simulateV1`), each call's `eth_call`/`eth_estimateGas` ran with the accumulated state overrides, but the `debug_traceCall` that produces the state diff for the next call did not. The diff was therefore computed against the raw latest chain state instead of the state the one before it produced. Because `mergeDiffIntoOverrides` stores absolute post-state slot values (not deltas), this breaks in two ways, both fixed by the same change:

1. A call that only succeeds because an earlier call set up state reverts inside the trace; its `post` diff comes back empty and later calls silently answer against stale state.
2. A call that succeeds even on the raw base state still yields absolute post-state slot values computed from the wrong base, and merging them overwrites the correct accumulated values.

Passing the accumulated snapshot to `debug_traceCall` fixes both; special-casing an empty `post` would fix neither.

## Change

`lib/execute/simulate-sequence.ts` (`runWithStateOverrides`):

- Pass the same `stateAtThisCall` snapshot to `debug_traceCall` as `stateOverrides` (geth's `StateOverride`, same per-account shape as `eth_call`'s third argument). Sent only when non-empty, so the first call's request is unchanged.
- Skip the trace for the last call: its diff seeds no next call, and it is the most expensive trace in the sequence because it carries the whole accumulated `stateOverrides`.
- The state-carry failure message now names the full failed request (the `prestateTracer` trace with the accumulated state overrides) rather than implying `prestateTracer` specifically is unsupported.

## Test plan

- [x] Request-shape regression test: in a three-call sequence, the first trace carries no `stateOverrides`, the second carries the first call's accumulated diff, and the final call's (unused) trace is not sent at all.
- [x] State-flow regression test with a state-dependent stub: the mock node's `prestateTracer` output varies with the `stateOverrides` it receives (raw-state slot vs carried-state slot). Asserts the third call's `eth_call` receives both slots, proving the accumulated state actually shaped the traced result. A constant-`post` stub cannot observe this. Fails on the pre-fix code (verified by reverting).
- [x] `tests/unit/execute-simulate-sequence.test.ts` — 14/14 pass (12 pre-existing + 2 new)
- [x] `tests/unit/execute-simulate.test.ts` — 38/38 pass
- [x] `tests/unit/contract-call-sequence.test.ts` — 9/9 pass
- [x] `pnpm type-check` clean, `pnpm check` clean (1 pre-existing warning)

## Files

- `lib/execute/simulate-sequence.ts` — trace each call against the accumulated state; skip the unused final trace; clarify the failure message
- `tests/unit/execute-simulate-sequence.test.ts` — two regression tests: request shape, and a state-dependent trace stub proving state actually flows

### CODE REVIEW

File: lib/execute/simulate-sequence.ts [hunk 1]
```diff
@@ -254,12 +254,24 @@ async function runWithStateOverrides(
     }
 
     try {
```
Comment (joelorzet) [inline lib/execute/simulate-sequence.ts:263]: The trace after the final call is never consumed. `overrides` is not read after the loop, so on a two-call run the measured traffic is `{eth_simulateV1:1, eth_call:2, eth_estimateGas:2, debug_traceCall:2}` and only trace #1's diff is used.

That wasted request is also the most expensive one in the sequence, because it carries the largest accumulated `stateOverrides` payload, which is what this PR adds. Under `executeWithFailover` with `maxRetries = 3` across primary and fallback it can cost up to six node round trips on its own. Skipping the trace when this is the last element is a one-line guard.

**Review by joelorzet — CHANGES_REQUESTED** [review]
The fix is correct and the regression test genuinely bites: reverting the diff in place turns `traces each call against the accumulated state` red. State accumulation is sound, `structuredClone` per iteration means a retry cannot mutate the accumulator, and the off-by-one in `unavailableRest` is exactly right.

I also probed the assumption the description hedges on, across 18 endpoint and method combinations on the configured public defaults: **every endpoint that answers `debug_traceCall` at all also accepts `stateOverrides`**, five for five, byte-identically. The field name matches geth's `TraceCallConfig.StateOverrides`. That hedge can come out of the description.

Worth knowing separately: on today's public defaults this path cannot produce an answer on any chain. The only chains missing `eth_simulateV1` are Avalanche (primary and fallback) and 0G primary, and none of those answers `debug_traceCall` either, so the fallback returns unavailable regardless. Every chain where the trace works already has `eth_simulateV1`. The fix is live only where managed endpoints are supplied through `CHAIN_RPC_CONFIG`, which is a reason to verify it against that set rather than a reason to hold it.

Two small asks.

The failing `check-issue-link` is not yours. Issue #2517 is filed but not yet labelled `accepted`, and that is maintainer triage on our side.

**`lib/execute/simulate-sequence.ts:294`**

This message names `prestateTracer`, and after this change it will also be emitted when the node answered `prestateTracer` perfectly well and rejected the `stateOverrides` key instead. Modelling that node on a three-call sequence:

```
results[2] = { failureKind: "unavailable",
  error: "Simulation unavailable: Could not carry state to this call:
          the node did not answer debug_traceCall with prestateTracer" }
```

Trace #1 succeeded and its diff was merged, so the stated cause is wrong and an operator would go hunting the wrong capability. Before this PR the text was accurate for the only failure it could describe.

The bare `catch {}` above also logs nothing, so there is no signal that a chain has begun degrading, and `mechanismByChain.set(chainId, "state-overrides")` pins it to this path for the process lifetime. Carrying the caught error into the message, or distinguishing the two causes, would fix both.

**`lib/execute/simulate-sequence.ts:243`**

Not introduced here, but it sits three lines above the diff and is worth closing while you are in this function.

A transport failure on the `eth_call` is reported to the caller as a revert. Injecting `ECONNRESET` on call 2:

```
wouldRevert: true
results[1] = { failureKind: "revert", revertReason: "connection reset by peer" }
```

The same input on the `eth_simulateV1` path throws out of `runSimulateV1` and returns `sequenceUnavailable` for the whole sequence. So the two mechanisms disagree on a node hiccup, and the fallback's answer is the one that tells a user their transaction would revert when nothing about the transaction is wrong.

Related, also pre-existing: `gasUsed` at `:242` comes from `eth_estimateGas`, a binary-searched minimum to succeed, while `:204` fills the same field from `eth_simulateV1`'s actual gas used. Both land in `gasEstimate`, so one field carries systematically different quantities depending on which mechanism ran.

File: lib/execute/simulate-sequence.ts (hunk 1 above)
Comment (grantyuan) [reply lib/execute/simulate-sequence.ts:263]: Good catch. Fixed in 42dd89b97: a `if (index === calls.length - 1) continue;` guard before the trace, so the final call no longer pays for a diff nothing consumes. The regression test now runs three calls so the second call's diff (the one that seeds the third call's `eth_call`) is still exercised, and it asserts exactly two trace requests are sent.

**Comment by grantyuan** [comment]
Both asks are addressed in 42dd89b97, and the description no longer carries the hedge.

1. Final-call trace: now skipped (`index === calls.length - 1`). The regression test was extended to a three-call sequence so the second call's diff (which seeds the third call's `eth_call`) is still covered, and it asserts exactly two trace requests are sent.

2. Failure message: it now reads "the node did not answer debug_traceCall with the prestateTracer trace and the accumulated state overrides" — accurate whether the node lacks prestateTracer or rejects stateOverrides, instead of sending an operator hunting the prestateTracer capability.

On the reachability note: agreed. With today's public defaults the fallback answers nothing on any chain (Avalanche and 0G lack eth_simulateV1 and do not answer debug_traceCall either), so this is a correctness fix for the CHAIN_RPC_CONFIG-managed-endpoint set rather than a live regression on the defaults. Happy to add a note to the code if that distinction is worth documenting for future readers.

Full re-verification on the new head: tests/unit/execute-simulate-sequence 13/13, execute-simulate 38/38, contract-call-sequence 9/9, type-check and check clean.

**Review by suisuss — CHANGES_REQUESTED** [review]
## What this changes

`runWithStateOverrides` indexes the loop and skips `debug_traceCall` on the final call, so an N-call sequence issues N-1 traces. `overrides` is never read after the loop, and had the last iteration's trace thrown, `unavailableRest(calls, results.length)` was called with `from === calls.length` and returned an empty array, so the results are identical for every input: this is one saved round trip, not a behaviour change. The `unavailable` message at `:301` now names the accumulated state overrides alongside the tracer. The regression test moves to a three-call sequence so two traces remain to assert on, and `toHaveLength(2)` now means "the last call was not traced", going red if the guard is reverted.

## Does it match the description

Undersells. The Change and Files sections still describe only the `stateOverrides` pass; neither the final-call skip nor the message rewrite appears in them. The defect framing is also narrower than what the code fixes: an empty `post` is not the only failure mode, because `mergeDiffIntoOverrides` stores absolute post-state slot values, so a trace that succeeded against raw `latest` wrote wrong absolutes over correct accumulated ones. Tracing on the snapshot fixes both cases, and the body is worth saying so.

## Previously raised

- Final-call trace: landed at `:259`, and it is output-preserving rather than only cheaper.
- `unavailable` message: reworded, but the `catch` still drops the node's error, which was the half of that ask that gives an operator something to act on. Below.
- `:243`, a transport failure on `eth_call` surfacing as `failureKind: "revert"`, and the `gasEstimate` mismatch between the two mechanisms: both still open and unanswered. They are pre-existing and outside #2517, so leave them here; I am filing them separately.

## Mechanical - actionable as-is

- `lib/execute/simulate-sequence.ts:286` - the catch is bare, so the node's own refusal is discarded and one sentence now covers three causes without naming which occurred: `debug_traceCall` or `prestateTracer` missing, `stateOverrides` rejected, or a transport failure after failover. A connection reset on the trace reads to an operator as a capability problem, and `mechanismByChain` keeps the chain pinned to this path for the process lifetime with nothing logged. `catch (err)` and carry `getErrorMessage(err)` through `unavailableRest` into the message, as `:247` already does on the `eth_call` side.
- Put the final-call skip and the message change in the description.

## Not this PR

`lib/execute/simulate-sequence.ts:349` - a slot a call clears to zero never leaves the accumulator. geth's prestateTracer writes `post.storage[key]` only when the new value is non-zero (`eth/tracers/native/prestate.go`, `processDiffState`), so a cleared slot sits in `pre` and is absent from `post`, and the additive merge keeps the stale non-zero value. `approve(vault, 1000)` then `deposit(1000)`, which drains the allowance, then a second `deposit`: call three simulates against an override still claiming an allowance of 1000 and reports success for a call that reverts on chain. Pre-existing, and once the trace runs on the right base it is the remaining hole in "each call against the state the one before it produced". Mine to file, not yours to fix here.

## Verdict

One line outstanding: the trace catch still discards the node's error, so the message says what class of thing failed but never which.

**Comment by grantyuan** [comment]
Follow-up addressing the review: commit `1c6a1c665` adds the state-dependent `debug_traceCall` stub you asked for in #2517 — the mock's `prestateTracer` output now varies with the `stateOverrides` it receives, so the test proves the accumulated state actually shaped the traced result (third call's `eth_call` must see both the raw-state and carried-state slots). Verified it goes red on the pre-fix code and green with the fix. PR description updated with the corrected framing (absolute post-state overwrite, not just the empty-`post` special case).

**Comment by grantyuan** [comment]
Pushed `5cef72d7e` — the last outstanding item:

- The `catch` around `debug_traceCall` now captures the error and carries `getErrorMessage(err)` through `unavailableRest` into the message (same pattern as the `eth_call` side at the call above), so an operator sees the node's actual refusal, e.g. `Could not carry state to this call: prestateTracer is not supported`, instead of only the failure class.
- The trace-failure regression test now asserts the node's error text surfaces in the `unavailable` result, locking the behavior in.

File: lib/execute/simulate-sequence.ts [hunk 2]
```diff
@@ -253,33 +253,63 @@ async function runWithStateOverrides(
...
       // Without the diff the next call sees state as if this one never ran,
       // which is the behaviour this whole path exists to avoid. Stop rather
-      // than return answers that silently mean something else.
-      results.push(...unavailableRest(calls, results.length));
+      // than return answers that silently mean something else. Carry the node's
+      // own error through so an operator can tell a capability refusal
+      // (prestateTracer or stateOverrides missing) from a transport failure.
+      results.push(
+        ...unavailableRest(calls, results.length, getErrorMessage(err))
+      );
```
Comment (joelorzet) [inline lib/execute/simulate-sequence.ts:294]: The PR body's third bullet still says the message "names the full failed request (the `prestateTracer` trace with the accumulated state overrides)". That was true of the earlier revision. At this head that string is only the fallback for an empty reason, and the actual behaviour, carrying the node's error through, is better and is not mentioned anywhere in the body.

Worth correcting so the next reader does not go looking for the old wording.

One thing still open on this path: nothing is logged server-side when a chain degrades onto the fallback, while `mechanismByChain` pins it there for the process lifetime. The message reaches the caller; an operator never learns a chain stopped answering `eth_simulateV1`. A `logSystemWarn` at the point the mechanism flips would close that.

For sequencing: #2544 fixes the transport-failure-reported-as-revert issue on this same file, and `git merge-tree` of the two heads produces a clean tree, so the two do not collide. #2545 does conflict with this PR and depends on it, so this one should land first.

**Review by joelorzet — CHANGES_REQUESTED** [review]
Both findings are fixed and I checked the second is output-preserving rather than just shorter. Against a stub node that answers `debug_traceCall` but rejects `stateOverrides`, the message now carries the node's own words:

```
"Could not carry state to this call: invalid argument 2: unknown field \"stateOverrides\""
```

Reverting the `getErrorMessage(err)` carry turns a case red. And with a stub that fails the third trace, head issues 2 traces where the unskipped build issues 3, with byte-identical result objects; removing the skip reddens the length assertion.

One thing left, and it is the description rather than the code.

**Comment by suisuss** [comment]
One piece of context you have no way to see from here: **this fix gates another contributor's pull request.**

`#2531` routes the workflow editor's preflight into `simulateCallSequence`, which means the missing `stateOverrides` on the `debug_traceCall` at `lib/execute/simulate-sequence.ts:259-263` stops being reachable only through `/api/execute/contract-call` with `calls[]` and becomes reachable from every workflow save. Two-call runs are unaffected, since the last diff is never consumed - it is three or more chained writes on a chain without `eth_simulateV1` that answer against the wrong base. I have asked there that the two be sequenced rather than raced, with this one first.

Not a request for anything, and not a nudge - the ball is with joelorzet's review from the 17th, after your `5cef72d7`. It just seemed worth knowing that this is on someone else's critical path.

File: lib/execute/simulate-sequence.ts (hunk 2 above)
Comment (grantyuan) [reply lib/execute/simulate-sequence.ts:295]: Both items addressed in 8f1963d31:

1. Description — the third bullet now says the message carries the node's own error text (with the `unknown field "stateOverrides"` example), and the generic wording is only the empty-reason fallback; the final-call skip, the message change, and the logging behaviour are all in Change/Files/Test plan.

2. Logging — a `logSystemWarn` (category `NETWORK_RPC`, `chainId` label) now fires at the flip, in the same `catch` where the pin happens, with the original error attached. It is the only log on that path: once `mechanismByChain` pins the chain, the cached path is silent, so a process logs the degradation exactly once per chain. New regression test asserts exactly one call with the expected category/label and that a second sequence on the pinned path logs nothing.

Local: tsgo clean, biome clean (1 pre-existing fixture-size warning), sequence file 15/15.

**Comment by grantyuan** [comment]
Ready for re-review: the two items outstanding from the 17th review are addressed in 8f1963d31.

- Description: the third bullet now describes the actual behaviour — the state-carry message carries the node's own error text (e.g. `Could not carry state to this call: invalid argument 2: unknown field "stateOverrides"`), and the previous wording is only the empty-reason fallback. The final-call trace skip, the message change, and the degradation log are all listed under Change/Files/Test plan.
- Logging: a `logSystemWarn` (category `NETWORK_RPC`, `chainId` label, original error attached) now fires once at the point the mechanism flips to the state-overrides fallback — in the same `catch` where `mechanismByChain` pins the chain. The pinned path stays silent, so a process logs the degradation exactly once per chain. New regression test: exactly one warning on the flip, none on the pinned path.

CI is green on the new head (test-unit, test-db, test-integration, lint, typecheck, build).

**Review by suisuss — CHANGES_REQUESTED** [review]
## What this changes

Two files. `lib/execute/simulate-sequence.ts` imports `ErrorCategory, logSystemWarn` at line 15 and calls `logSystemWarn` at 505-510, after the `isMethodNotFound` guard and before `mechanismByChain.set(chainId, "state-overrides")` at 512. No control flow moves. `tests/unit/execute-simulate-sequence.test.ts` adds `logSystemWarn` and `ErrorCategory.NETWORK_RPC` to the `@/lib/logging` mock, imports the mocked function, and asserts one warn on the first degradation and still one after a second run.

## Does it match the description

Matches. The body's four bullets are all present at head, and the third now describes the error-text behaviour rather than the earlier wording.

Both items from the 17th are addressed:

- Skip the trace on the last call - done at 257-262, with the reason stated.
- Log the degradation server-side - done at 505-510.

I re-read the headline fix at head rather than assuming it from the increment: 274-276 set `traceOptions.stateOverrides = stateAtThisCall` when the snapshot is non-empty and pass it as the third `debug_traceCall` argument. That is the fix, and it is correct.

## Mechanical - actionable as-is

- `lib/execute/simulate-sequence.ts:509` - the label is written as `chainId`, and every other label key in the codebase is snake_case: `LabelKeys` (`lib/metrics/types.ts:226`) is `workflow_id`, `execution_id`, `org_id`, `error_category` throughout, and `chain_id: String(chainId)` appears at 21 call sites against 2 for `chainId: String(chainId)`. An operator filtering Loki with `| json | chain_id="8453"` gets nothing back for exactly the chains this line exists to surface. Rename to `chain_id`, and change the assertion at `tests/unit/execute-simulate-sequence.test.ts:422`, which currently pins the wrong key.

- `lib/execute/simulate-sequence.ts:504` - the comment says the flip is logged "once", and the call sits before `mechanismByChain.set` at 512 with no in-flight guard. Two concurrent sequence requests for the same chain on a cold process both read the mechanism as unset, both reject, and both log. The bound is concurrency at first use, so this is a wording fix rather than a lock: "once per process per chain, best-effort" describes what the code does.

## Verdict

Changes requested - the log label does not match the key every other call site uses, and the new test pins it.

**Comment by grantyuan** [comment]
Both items from the 21st review are addressed in 86b320cf7:

1. Label key — lib/execute/simulate-sequence.ts:510 now emits `{ chain_id: String(chainId) }`, matching the snake_case keys in `LabelKeys` (lib/metrics/types.ts:226) and the `chain_id: String(chainId)` call sites, so a Loki filter on `chain_id` picks these events up. The assertion at tests/unit/execute-simulate-sequence.test.ts:422 now pins `{ chain_id: "84532" }`.

2. Wording — the comment above the log now says "once per process per chain, best-effort (a concurrent first-use race can log it twice)" instead of "once".

Local: sequence file 15/15, tsgo clean, biome clean (1 pre-existing fixture-size warning).

**Comment by suisuss** [comment]
## What this changes

`lib/execute/simulate-sequence.ts:510` now labels the one-time degradation warning `{ chain_id: String(chainId) }`, matching the snake_case keys in `LabelKeys` (`lib/metrics/types.ts`), so a Loki filter on `chain_id` returns these events. The comment at 504-505 now reads "once per process per chain, best-effort" and names the concurrent first-use race. `tests/unit/execute-simulate-sequence.test.ts:422` pins the new key. No control flow moves.

## Does it match the description

Matches. The Test plan's degradation-logging bullet still says "`chainId` label".

## Previously raised

- Label key renamed to `chain_id` - addressed at `lib/execute/simulate-sequence.ts:510` and `tests/unit/execute-simulate-sequence.test.ts:422`.
- "Once" wording - addressed at `lib/execute/simulate-sequence.ts:504-505`.

## Mechanical - actionable as-is

- Description, Test plan - "`chainId` label" should read "`chain_id` label". Optional; nothing waits on it.

## Verdict

Nothing blocking - handing this on for final review.
