### ISSUE TITLE
fix: simulate-sequence's state-overrides fallback traces calls against raw state, dropping earlier calls' writes

### ISSUE THREAD

**Issue by grantyuan** [KeeperHub/keeperhub#2517]
## Where

`lib/execute/simulate-sequence.ts`, `runWithStateOverrides` — the fallback path for chains whose RPC does not implement `eth_simulateV1`, introduced by #2452 (#2427).

For every call in the sequence, the loop runs:

1. `eth_call` and `eth_estimateGas` **with** `stateAtThisCall` (the accumulated state overrides from all earlier calls) — correct.
2. `debug_traceCall` with `prestateTracer` + `diffMode: true` to produce the state diff that seeds the next call — **without** any overrides:

```ts
provider.send("debug_traceCall", [
  tx,
  "latest",
  { tracer: "prestateTracer", tracerConfig: { diffMode: true } },
])
```

So the diff is computed against the raw `latest` chain state, not against the state the call was actually simulated against.

## Reason

`debug_traceCall` accepts `stateOverrides` in its options object (same per-account shape as `eth_call`'s third argument; geth `StateOverride`), so tracing against the accumulated state is supported. Without it:

- Any call that only succeeds because an earlier call set up state (approve before transferFrom, set-config before use, ...) **reverts inside the trace** even though the `eth_call` directly above it (run with the overrides) succeeded.
- Its `post` diff is then empty or wrong, `mergeDiffIntoOverrides` merges nothing, and every later call silently answers against state that lacks the earlier calls' writes.

The answer is internally inconsistent: the sequence reports call N as success (from the overridden `eth_call`) while not carrying call N's state into call N+1. That is exactly the failure mode this fallback exists to avoid — the feature's commit message says a node offering neither mechanism should report the later calls as unavailable "rather than quietly answering against latest state".

## Scope

- Fallback path only (chains without `eth_simulateV1`); the primary path is unaffected.
- Only from the 2nd call onward: the first call has nothing to carry, and a 2-call sequence never consumes the last call's diff — so the canonical approve→deposit pair answers correctly today.
- 3+ call sequences where an intermediate call depends on earlier state are wrong (e.g. approve → transferFrom → read balance: the read returns the pre-transfer balance). `MAX_SEQUENCE_CALLS` is 10, so this is reachable through `POST /api/execute/contract-call` with `simulate: true` and `calls[]`.

## Proposed fix

Pass the same snapshot to the trace:

```ts
{
  tracer: "prestateTracer",
  tracerConfig: { diffMode: true },
  ...(Object.keys(stateAtThisCall).length > 0 && { stateOverrides: stateAtThisCall }),
}
```

If a node that supports `debug_traceCall` rejects `stateOverrides`, the existing catch already degrades the remaining calls to `unavailable` — better than state-blind answers.

## Test

Assert in `tests/unit/execute-simulate-sequence.test.ts` that the second `debug_traceCall` request carries the first call's accumulated `stateOverrides`, while the first request sends none.

**Comment by suisuss** [comment]
Confirmed. `eth_call` and `eth_estimateGas` get `stateAtThisCall`; the `debug_traceCall` three lines below gets nothing, so the diff that seeds the next call is computed against raw `latest`. Whatever comes back is merged without complaint - an empty `post` is a silent no-op in `mergeDiffIntoOverrides` - so the sequence reports call N as a success and carries none of its writes into call N+1.

One correction to the framing. The "unavailable rather than quietly answering against latest state" line is scoped to a node offering neither mechanism, and that case is handled: the `catch` around the trace does degrade the rest. What this actually breaks is the sentence beside it in `docs/api/direct-execution.md`, that the `state-overrides` fallback gives "the same answer", and the endpoint's own promise of "an ordered sequence, each call against the state the one before it produced". It also bites wider than a revert inside the trace: `mergeDiffIntoOverrides` stores absolute post-state slot values, so a call that merely traces against the wrong base writes wrong absolutes over the accumulated ones even when it succeeds.

Scope otherwise holds, including approve-then-deposit being unaffected because its last diff is never consumed. Passing the accumulated snapshot to `debug_traceCall` is the change I want.

**Comment by suisuss** [comment]
Two things I should have put in the first comment, both of which widen the fix.

`mergeDiffIntoOverrides` writes absolute post-state slot values into `stateDiff`, not deltas. An empty `post` is therefore not the only way this goes wrong: a call whose trace against raw `latest` *succeeds* still yields slot values computed from the wrong base, and merging them overwrites correct accumulated values. Passing the snapshot to `debug_traceCall` fixes both cases; special-casing an empty `post` fixes neither.

No test in `tests/unit/execute-simulate-sequence.test.ts` can catch either today. `run()` defaults to the two-call `APPROVE_THEN_DEPOSIT` fixture, the one three-call case repeats `APPROVE_THEN_DEPOSIT[0]`, and the `debug_traceCall` stub returns a fixed `post` whatever params it is handed, so it cannot observe whether overrides were passed at all. A regression test needs a stub whose `post` varies with its third argument.

One correction on the quote, since it also appears in #2518: the promise about reporting later calls as unavailable is scoped to a node offering neither mechanism, and that case is handled - the `catch` around the trace returns `unavailableRest` for the remainder of the sequence. The promise this breaks is the one beside it, that each call resolves against the state the one before it produced.

**Comment by grantyuan** [comment]
Thanks for confirming and for the sharper framing — you are right on both counts:

1. **Framing**: the promise that is actually broken is the "same answer / each call resolves against the state the one before produced" one (docs/api/direct-execution.md and the endpoint contract), not the "report unavailable when the node offers neither mechanism" fallback, which the catch around the trace does handle. And the absolute-post-state point matters: a call that *succeeds* on a trace against the raw base would write wrong absolute slot values over the correct accumulated ones — an empty `post` is only the special case of that. The fix (passing the accumulated snapshot to `debug_traceCall`) addresses both; special-casing an empty `post` would fix neither. I have updated the PR description to use this framing.

2. **State-dependent test**: commit `1c6a1c665` on the PR adds exactly that — a `debug_traceCall` stub whose `post` varies with its third argument (the `stateOverrides` it is handed): on raw latest state it reports slot `0xraw`, and when the request already carries the TOKEN entry it reports `0xcarried` instead. The test runs a three-call sequence and asserts the third call's `eth_call` receives **both** slots (`0xraw` from the first call's trace, `0xcarried` only producible if the second call's trace ran on top of the first call's state). Verified: with the fix reverted both regression tests go red; with it, all 14 pass.

PR: https://github.com/KeeperHub/keeperhub/pull/2518

**Comment by suisuss** [comment]
Agreed on both, and the test does what you say it does.

I read it at head (`8f1963d3`) rather than taking it from the increment. `tests/unit/execute-simulate-sequence.test.ts:340` keys the stub's `post` off `params[2].stateOverrides`, so against the pre-fix code, which sends only `{ tracer, tracerConfig }` (`lib/execute/simulate-sequence.ts:259-263` on staging), the second call's trace can only ever return `0xraw`, the merge at `:266` is a no-op, and the assertion at `tests/unit/execute-simulate-sequence.test.ts:389` goes red. A constant-`post` stub cannot tell those two worlds apart, which was the gap.

The absolute-value point is visible at `lib/execute/simulate-sequence.ts:332-335`: `entry.stateDiff` spreads the traced `storage` over what has already accumulated, so a trace run against the wrong base overwrites correct values with wrong ones whether or not it reverted. Nothing about the plan changes.

I am leaving this open until #2518 lands. The outstanding review is on the PR and concerns the label key on the new degradation warning, not this fix.
